-- ------------------------------------------------- PROCEDURES -----------------------------


  -- ACTUALIZA CLIENTE --
CREATE PROCEDURE `UPDATE_CLIENTE` (`PREV_NIT` VARCHAR(15),`NIT_CLIENTE` VARCHAR(15),`NC_IN` VARCHAR(45),`AC_IN` VARCHAR(45),`TC_IN` VARCHAR(15),`TEC_IN` VARCHAR(15), `DIAS` INT, `LIMITE` FLOAT) 
  UPDATE CLIENTE SET ESTADO_TUPLA = TRUE,
  ID_CLIENTE = NIT_CLIENTE,
  NOMBRE_CLIENTE = NC_IN,
  APELLIDO_CLIENTE = AC_IN,
  TELEFONO_CLIENTE = TEC_IN,
  ID_TIPO_CLIENTE = (SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TC_IN LIMIT 1),
  LIMITE_CREDITO = LIMITE,
  DIAS_CREDITO = DIAS
  WHERE ID_CLIENTE = PREV_NIT;


 -- SP ELIMINA CLIENTE --
CREATE PROCEDURE `ELIMINAR_CLIENTE` (`NIT_CLIENTE` VARCHAR(15)) 
  UPDATE CLIENTE SET ESTADO_TUPLA = FALSE WHERE ID_CLIENTE = NIT_CLIENTE;


 -- SP PARA INGRESO CLIENTE --
CREATE PROCEDURE `INGRESO_CLIENTE` (`ID_CLIENTE` VARCHAR(15), `NOMBRE_CLIENTE` VARCHAR(45),`APELLIDO_CLIENTE` VARCHAR(45),`TELEFONO_CLIENTE` VARCHAR(15),`LIMITE` FLOAT,`DIAS` INT,`TIPO_C` VARCHAR(45)) 
 INSERT INTO CLIENTE VALUES (ID_CLIENTE,(SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TIPO LIMIT 1),NOMBRE_CLIENTE,APELLIDO_CLIENTE,TELEFONO_CLIENTE,LIMITE,DIAS,TRUE);



-- SP ELIMINA PROVEEDOR --
CREATE PROCEDURE `ELIMINAR_PROVEEDOR` (`ID_PD` INT) 
  UPDATE PROVEEDOR SET ESTADO_TUPLA = FALSE WHERE ID_PROVEEDOR = ID_PD;

 -- SP PARA INGRESO PROVEEDOR --
CREATE PROCEDURE `INGRESO_PROVEEDOR` (`NOMBRE_PROVEEDOR` VARCHAR(45),`EMAIL_PROVEEDOR` VARCHAR(45),`DIR_PROVEEDOR` VARCHAR(45),`TELEFONO_PROVEEDOR` INT) 
 INSERT INTO PROVEEDOR VALUES (NULL,NOMBRE_PROVEEDOR,EMAIL_PROVEEDOR,DIR_PROVEEDOR,TELEFONO_PROVEEDOR,TRUE);


  -- SP ACTUAIZA PROVEEDOR --
CREATE PROCEDURE `UPDATE_PROVEEDOR` (`ID_PD` INT,`NM_PROVEEDOR` VARCHAR(45),`EM_PROVEEDOR` VARCHAR(45),`DIR_PROVEEDOR` VARCHAR(45),`TEL_PROVEEDOR` INT) 
  UPDATE PROVEEDOR SET ESTADO_TUPLA = TRUE,
  NOMBRE_PROVEEDOR = NM_PROVEEDOR,
  EMAIL_PROVEEDOR = EM_PROVEEDOR,
  DIRECCION_PROVEEDOR = DIR_PROVEEDOR,
  TELEFONO_PROVEEDOR = TEL_PROVEEDOR
  WHERE ID_PROVEEDOR = ID_PD;
  
CREATE PROCEDURE `UPDATE_SUCURSAL` (`SUCURSAL` INT,`NOMBRE` VARCHAR(45),`DIRECCION` VARCHAR(45),`TELEFONO` VARCHAR(45),`TIPO` VARCHAR(45)) 
  UPDATE SUCURSAL SET 
  NOMBRE_SUCURSAL = NOMBRE,
  DIRECCION_SUCURSAL = DIRECCION,
  TELEFONO_SUCURSAL = TELEFONO,
  ID_TIPO = (SELECT ID_TIPO FROM TIPO_SUCURSAL WHERE TIPO_SUCURSAL = TIPO LIMIT 1)
  WHERE ID_SUCURSAL = SUCURSAL;
  

 
 -- ------ CONTROL DE MERCADERIA --------------------------------------------------------------------

CREATE PROCEDURE `INGRESA_MERCADERIA` (`CODIGO` VARCHAR(20),`SUCURSAL` INT,`PROVEEDOR` VARCHAR(45),`DESCR` VARCHAR(45),
`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,SUCURSAL,1,
    (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);
     

CREATE PROCEDURE `INGRESA_ESPECIAS` (`CODIGO` VARCHAR(20),`SUCURSAL` INT,`PROVEEDOR` VARCHAR(45),`DESCR` VARCHAR(45),
`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,SUCURSAL,2,
    (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);
     

CREATE PROCEDURE `INGRESA_STOCK` (`ID_STOCK` VARCHAR(10),`ID_MERCADERIA` VARCHAR(20), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE)
    INSERT INTO MERCADERIA_PRESENTACIONES VALUES (ID_STOCK, ID_MERCADERIA,1001,DESCR,CANTIDAD_PP,TOTAL_P,CANT_M,
    P_1,P_2,P_3,P_4,UT_1,UT_2,NOW(),TRUE);
    
    

CREATE PROCEDURE `UPDATE_MERCADERIA` (`CODIGO` VARCHAR(20),`PRECIO_C` FLOAT, `TOTAL_U` FLOAT)
 UPDATE MERCADERIA SET 
  PRECIO_COMPRA = PRECIO_C,
  TOTAL_UNIDADES = TOTAL_UNIDADES + TOTAL_U
  WHERE ID_MERCADERIA = CODIGO AND ID_SUCURSAL = 1001;


CREATE PROCEDURE `UPDATE_STOCK` (`ID_ST` VARCHAR(10),`ID_MERC` VARCHAR(20), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE)
    UPDATE MERCADERIA_PRESENTACIONES SET
    DESCRIPCION = DESCR,
    CANTIDAD_POR_PRESENTACION = CANTIDAD_PP,
    TOTAL_PRESENTACIONES = TOTAL_P,
    CANTIDAD_MINIMA = CANT_M,
    PRECIO_1 = P_1,
    PRECIO_2 = P_2,
    PRECIO_3 = P_3,
    PRECIO_4 = P_4,
    UTILIDAD_1 = UT_1,
    UTILIDAD_2 = UT_2
    WHERE ID_STOCK = ID_ST AND ID_MERCADERIA = ID_MERC;
    
    CREATE PROCEDURE `NUEVA_COMPRA` (`ID_C` INT,`USER_S` VARCHAR(25))
     INSERT INTO COMPRA VALUES (ID_C,USER_S,NOW(),0,0,0,0,TRUE);
     
     
	CREATE PROCEDURE `DETALLE_COMPRA` (`ID_COM` INT,`ID_MERC` VARCHAR(20),`CANTIDAD` FLOAT,`GASTOS` FLOAT, `SUBTOTAL` FLOAT)
     INSERT INTO CONTROL_COMPRA VALUES (NULL,ID_COM,ID_MERC,CANTIDAD,GASTOS,SUBTOTAL);
     

    CREATE PROCEDURE `GET_COMPRA` (`ID_COM` INT)
     SELECT  C.SUBTOTAL FROM CONTROL_COMPRA C WHERE ID_COMPRA = ID_COM;
	
    CREATE PROCEDURE `CIERRA_COMPRA` (`ID_C` INT,`SUBTOTAL` FLOAT, `DESCUENTOS` FLOAT, `TOTAL` FLOAT)
     UPDATE COMPRA SET 
     SUBTOTAL_COMPRA = SUBTOTAL,
     DESCUENTO  = DESCUENTOS,
     TOTAL_FINAL = TOTAL
     WHERE ID_COMPRA = ID_C;
      




