
-- ---------------------------------  VISTAS EN C# --------------------------------------------------------

CREATE VIEW -- VISTA CLIENTES DATAGRIDVIEW ----
VISTA_CLIENTES AS
SELECT C.ID_CLIENTE, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE,C.TELEFONO_CLIENTE, T.TIPO, C.LIMITE_CREDITO, C.DIAS_CREDITO FROM CLIENTE C
INNER JOIN TIPO_CLIENTE T
ON C.ID_TIPO_CLIENTE = T.ID_TIPO_CLIENTE AND C.ESTADO_TUPLA = TRUE;

CREATE VIEW    -- VISTA PROVEEDORES DATAGRIDVIEW --
VISTA_PROVEEDORES AS
SELECT P.ID_PROVEEDOR,P.NOMBRE_PROVEEDOR,P.EMAIL_PROVEEDOR,P.DIRECCION_PROVEEDOR,P.TELEFONO_PROVEEDOR FROM PROVEEDOR P 
WHERE P.ESTADO_TUPLA = TRUE;



CREATE VIEW    -- VISTA PROVEEDORES DATAGRIDVIEW --
VISTA_SUCURSALES AS
SELECT S.ID_SUCURSAL,(SELECT T.TIPO_SUCURSAL FROM TIPO_SUCURSAL T WHERE ID_TIPO = S.ID_TIPO),S.NOMBRE_SUCURSAL,S.DIRECCION_SUCURSAL,S.TELEFONO_SUCURSAL FROM SUCURSAL S
WHERE S.ESTADO_TUPLA = TRUE;


CREATE VIEW   -- VISTA STOCK DATAGRIDVIEW --
VISTA_MERCADERIA AS 
SELECT M.ID_MERCADERIA,P.NOMBRE_PROVEEDOR, M.DESCRIPCION,M.ACTIVO,M.PRECIO_COMPRA, M.TOTAL_UNIDADES, M.ID_CLASIFICACION, M.ID_SUCURSAL
FROM MERCADERIA M 
INNER JOIN PROVEEDOR P 
ON P.ID_PROVEEDOR = M.ID_PROVEEDOR AND M.ESTADO_TUPLA = TRUE;



CREATE VIEW 
VISTA_STOCK AS 
SELECT S.ID_STOCK, S.DESCRIPCION, S.CANTIDAD_POR_PRESENTACION, S.TOTAL_PRESENTACIONES,S.CANTIDAD_MINIMA,S.PRECIO_1,
S.PRECIO_2, S.PRECIO_3,S.PRECIO_4,S.UTILIDAD_1,S.UTILIDAD_2,S.ID_MERCADERIA,S.ID_SUCURSAL
 FROM MERCADERIA_PRESENTACIONES S WHERE S.ESTADO_TUPLA = TRUE;
 
 
CREATE VIEW 
VISTA_CONTROL_COMPRA  AS
 SELECT  C.ID_MERCADERIA, M.DESCRIPCION,C.CANTIDAD_COMPRA, M.PRECIO_COMPRA, C.OTROS_GASTOS, C.SUBTOTAL, C.ID_COMPRA  FROM  CONTROL_COMPRA C
  INNER JOIN MERCADERIA M 
  WHERE C.ID_MERCADERIA = M.ID_MERCADERIA;
  
CREATE VIEW 
 VISTA_COMPRA AS
  SELECT C.ID_COMPRA, C.FECHA_COMPRA, C.SUBTOTAL_COMPRA, C.DESCUENTO, C.TOTAL_FINAL, C.ID_USUARIO FROM COMPRA C 
  WHERE C.ESTADO_TUPLA = TRUE ORDER BY  FECHA_COMPRA DESC;

CREATE VIEW 
 VISTA_MERCADERIA_C AS
  SELECT M.ID_MERCADERIA, S.NOMBRE_SUCURSAL, F.TIPO_MERCADERIA, P.NOMBRE_PROVEEDOR, M.DESCRIPCION, M.PRECIO_COMPRA,
  M.TOTAL_UNIDADES,M.ACTIVO, M.FECHA_INGRESO, S.ID_SUCURSAL FROM MERCADERIA M 
  INNER JOIN SUCURSAL S
  ON S.ID_SUCURSAL = M.ID_SUCURSAL
  INNER JOIN CLASIFICACION_MERCADERIA F 
  ON F.ID_TIPO = M.ID_CLASIFICACION
  INNER JOIN PROVEEDOR P 
  ON P.ID_PROVEEDOR = M.ID_PROVEEDOR;
  
select * from vista_mercaderia_c;
  
 
 CREATE VIEW 
  TOTAL_PRODUCTOS_SUC1 
  AS SELECT COUNT(*) FROM MERCADERIA WHERE ID_SUCURSAL = 1001 AND ESTADO_TUPLA = TRUE;

